services:
  packet_copilot:
    image: johncapobianco/packet_copilot:packet_copilot
    container_name: packet_copilot
    restart: always
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile.packet
    expose:
      - "8501"
      - "8000"

  # configurationvision:
  #   image: johncapobianco/topology_vision:topology_vision
  #   container_name: topology_vision
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile.vision
  #   expose:
  #     - "8502"

  configuration_copilot:
    image: johncapobianco/configuration_copilot:configuration_copilot
    container_name: configuration_copilot
    restart: always
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile.configuration
    expose:
      - "8502"
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - packet_copilot
      # - configurationvision
      - configuration_copilot
